# Generated by Django 4.0 on 2021-12-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0002_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='guest',
            field=models.EmailField(default=0, max_length=254, verbose_name='guest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
