# Generated by Django 4.0 on 2021-12-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0004_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
